# Generated by Django 5.1 on 2026-10-04 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('auto', 'Auto Detect'), ('sw', 'Kiswahili'), ('en', 'English')], default='auto', max_length=10)),
                ('modality', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('sms_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Session',
                'verbose_name_plural': 'Conversation Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=10)),
                ('tool_name', models.CharField(max_length=80)),
                ('args', models.JSONField(default=dict)),
                ('ok', models.BooleanField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='konnect_ai.conversationsession')),
            ],
            options={
                'verbose_name': 'AI Audit Log',
                'verbose_name_plural': 'AI Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='konnect_ai__user_id_a901c6_idx'), models.Index(fields=['tool_name', 'created_at'], name='konnect_ai__tool_na_d5ce48_idx')],
            },
        ),
    ]
