"""Utility functions for loading market price CSV files generated by the KAMIS ETL.

The CSV files are stored in ``settings.MARKET_DATA_DIR`` and follow the
header ``commodity,county,date,wholesale_price,retail_price``.
"""

import csv
import logging
from pathlib import Path
from typing import List, Dict, Any

from django.conf import settings

logger = logging.getLogger(__name__)

# Resolve the directory – settings may define ``MARKET_DATA_DIR``; fallback to
# ``BASE_DIR / 'market_data'``.
DATA_DIR = getattr(settings, "MARKET_DATA_DIR", Path(settings.BASE_DIR) / "market_data")


def _latest_csv_path() -> Path | None:
    """Return the newest ``prices_*.csv`` file in ``DATA_DIR`` or ``None``.
    """
    if not DATA_DIR.exists():
        logger.warning("Market data directory %s does not exist", DATA_DIR)
        return None
    csv_files = sorted(DATA_DIR.glob("prices_*.csv"), reverse=True)
    return csv_files[0] if csv_files else None


def load_prices_from_csv(commodity: str | None = None, county: str | None = None) -> List[Dict[str, Any]]:
    """Read the latest CSV and optionally filter by commodity and county.

    Returns a list of dictionaries with the same keys as the CSV header.
    """
    path = _latest_csv_path()
    if not path:
        logger.warning("No market CSV files found in %s", DATA_DIR)
        return []
    results: List[Dict[str, Any]] = []
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if commodity and row["commodity"].upper() != commodity.upper():
                continue
            if county and row["county"].lower() != county.lower():
                continue
            results.append(row)
    return results
